language: python

python:
  - "3.7"

services:
  - postgresql
  - docker

addons:
  chrome: stable
  sonarcloud:
    organization: "sartography"

before_install:
  - cp config/travis-testing.py config/testing.py
  - psql -c 'create database crc_test;' -U postgres

install:
  - pip install pipenv pytest coverage
  - pipenv install
  - pytest              # <== This runs in Pipenv (a/k/a virtualenv)

# command to run tests
script:
  - coverage run -m pytest
  - coverage xml -i
  - sonar-scanner

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
