language: python

python:
  - "3.7"

services:
  - postgresql
  - docker

addons:
  chrome: stable
  sonarcloud:
    organization: "sartography"

before_install:
  - cp config/travis-testing.py config/testing.py
  - psql -c 'create database crc_test;' -U postgres

install:
  - pip install pipenv pytest coverage awscli
  - export PATH=$PATH:$HOME/.local/bin;
  - pipenv install

env:
  - PB_BASE_URL='http://workflow.sartography.com:5001/pb/'

script:
  - pipenv run coverage run -m pytest
  - pipenv run coverage xml -i

after_success:
  - sonar-scanner

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - dan@sartography.com
